---
name: yambs
version: "{{major}}.{{minor}}.{{patch}}"
description: Yet another meta build-system.
entry: {{entry}}
time_command: true

ci_local:
  - "- uses: seanmiddleditch/gha-setup-ninja@master"
  - "  with: {version: 1.11.1}"
  - "  if: matrix.system == 'ubuntu-latest'"

  - "- run: pip${{'{{matrix.python-version}}'}} install -e ."
  - "- run: mk python-editable"
  - "  if: matrix.system == 'ubuntu-latest'"

requirements:
  - datazen
  - vcorelib>=2.4.2
  - rcmpy>=1.5.0
  - requests
dev_requirements:
  - setuptools-wrapper
  - types-setuptools
  - types-requests

commands:
  - name: compile_config
    description: load configuration data and write results to a file
  - name: dist
    description: create a source distribution
  - name: download
    description: download GitHub release assets
  - name: gen
    description: poll the source tree and generate any new build files
  - name: native
    description: generate build files for native-only target projects
  - name: uf2conv
    description: convert to UF2 or flash directly
