---
name: yambs
version: "{{major}}.{{minor}}.{{patch}}"
description: Yet another meta build-system.
entry: {{entry}}
requirements:
  - datazen
  - vcorelib
  - rcmpy>=1.5.0
dev_requirements:
  - setuptools-wrapper
  - types-setuptools

commands:
  - name: gen
    description: poll the source tree and generate any new build files
